1. Problem: Implement the K-nearest neighbors (KNN) algorithm from scratch. Given a dataset and a query point, classify the query based on the majority label of its k-nearest neighbors.

In [6]:
import numpy as np
from collections import Counter

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        predictions = [self._predict(x) for x in X]
        return np.array(predictions)

    def _predict(self, x):
        distances = np.sqrt(np.sum((self.X_train - x) ** 2, axis=1))
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]

X_train = np.array([[1, 2], [2, 3], [3, 4], [5, 6]])
y_train = np.array([0, 0, 1, 1])
knn = KNN(k=3)
knn.fit(X_train, y_train)
print(knn.predict(np.array([[3, 3], [6, 5]])))

[0 1]


2. Problem: Implement logistic regression in Python. Include training using gradient descent, and calculate class probabilities for binary classification.

In [5]:
class LogisticRegression:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iterations):
            linear_model = np.dot(X, self.weights) + self.bias
            y_predicted = self.sigmoid(linear_model)

            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self.sigmoid(linear_model)
        class_labels = [1 if i > 0.5 else 0 for i in y_predicted]
        return np.array(class_labels)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
X_train = np.array([[0, 0], [1, 1], [1, 0], [0, 1]])
y_train = np.array([0, 1, 1, 0])
model = LogisticRegression()
model.fit(X_train, y_train)
print(model.predict(np.array([[0.5, 0.5], [1, 1]])))

[1 1]


3. Problem: Write a function to perform matrix multiplication without using external libraries like NumPy. Multiply two matrices representing weight matrices and input vectors in a neural network layer.

In [4]:
def matrix_multiply(A, B):
    # Check if A's columns match B's rows
    if len(A[0]) != len(B):
        raise ValueError("Cannot multiply, incompatible dimensions.")
    
    result = [[0] * len(B[0]) for _ in range(len(A))]
    
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    
    return result
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
print(matrix_multiply(A, B))

[[19, 22], [43, 50]]


4. Problem: Write a Python function that deep copies a neural network represented as a
nested list of layers, where each layer contains weight matrices.

In [7]:
def deep_copy_neural_network(network):
    return [layer.copy() for layer in network]
network = [[1, 2], [3, 4]]
new_network = deep_copy_neural_network(network)
print(new_network)

[[1, 2], [3, 4]]


5. Problem: Implement a moving average filter for a time series. Given a series of numbers
and a window size, return the moving average of the series.

In [9]:
def moving_average(data, window_size):
    if window_size < 1:
        raise ValueError("Window size must be at least 1")
    
    averages = []
    for i in range(len(data) - window_size + 1):
        window = data[i:i + window_size]
        averages.append(sum(window) / window_size)
    
    return averages
    
data = [1, 2, 3, 4, 5]
print(moving_average(data, 3))

[2.0, 3.0, 4.0]


6. Problem: Write a Python function that applies the ReLU activation function to a list of
inputs.

In [10]:
def relu(inputs):
    return [max(0, x) for x in inputs]
inputs = [-1, 2, -3, 4]
print(relu(inputs))

[0, 2, 0, 4]


7. Problem: Implement gradient descent to train a linear regression model. Minimize the
mean squared error by adjusting the model weights iteratively.

In [11]:
class LinearRegression:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)

        for _ in range(self.n_iterations):
            y_predicted = np.dot(X, self.weights)
            error = y_predicted - y
            gradients = (2 / n_samples) * np.dot(X.T, error)
            self.weights -= self.learning_rate * gradients

    def predict(self, X):
        return np.dot(X, self.weights)

X_train = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y_train = np.array([1, 2, 2, 3])
model = LinearRegression()
model.fit(X_train, y_train)
print(model.predict(np.array([[3, 5]])))

[4.95494716]


8. Problem: Write a Python function to perform one-hot encoding of categorical labels for a machine learning task.

In [12]:
def one_hot_encode(labels):
    unique_labels = list(set(labels))
    encoding = {label: idx for idx, label in enumerate(unique_labels)}
    one_hot = np.zeros((len(labels), len(unique_labels)))

    for i, label in enumerate(labels):
        one_hot[i][encoding[label]] = 1

    return one_hot
labels = ['cat', 'dog', 'cat', 'bird']
print(one_hot_encode(labels))

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


9. Problem: Implement a Python function to calculate the cosine similarity between two
vectors, which is often used in text similarity tasks.

In [13]:
def cosine_similarity(vec1, vec2):
    dot_product = sum(a * b for a, b in zip(vec1, vec2))
    norm_a = sum(a ** 2 for a in vec1) ** 0.5
    norm_b = sum(b ** 2 for b in vec2) ** 0.5
    return dot_product / (norm_a * norm_b) if norm_a and norm_b else 0.0
    
vec1 = [1, 2, 3]
vec2 = [4, 5, 6]
print(cosine_similarity(vec1, vec2))

0.9746318461970762


10. Problem: Given a trained neural network in Python, write a function to prune the network by removing neurons that have small or zero weights.

In [14]:
def prune_neurons(network, threshold=0.01):
    pruned_network = []
    for layer in network:
        pruned_layer = [[weight if abs(weight) > threshold else 0 for weight in neuron] for neuron in layer]
        pruned_network.append(pruned_layer)
    return pruned_network

network = [[[0.1, 0.2], [0.0, 0.3]], [[0.4, 0.0], [0.5, 0.6]]]
print(prune_neurons(network))

[[[0.1, 0.2], [0, 0.3]], [[0.4, 0], [0.5, 0.6]]]


11. Problem: Implement a Python function to compute the confusion matrix given true and
predicted labels for a classification task.

In [15]:
def confusion_matrix(true_labels, predicted_labels):
    classes = list(set(true_labels))
    matrix = np.zeros((len(classes), len(classes)), dtype=int)

    for true, pred in zip(true_labels, predicted_labels):
        matrix[classes.index(true)][classes.index(pred)] += 1

    return matrix

true_labels = [0, 1, 0, 1, 1]
predicted_labels = [0, 0, 1, 1, 1]
print(confusion_matrix(true_labels, predicted_labels))

[[1 1]
 [1 2]]


12. Problem: Write a Python function that performs mini-batch gradient descent for optimizing the weights of a neural network.

In [17]:
class MiniBatchGradientDescent:
    def __init__(self, learning_rate=0.01, n_iterations=1000, batch_size=32):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.batch_size = batch_size
        self.weights = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)

        for _ in range(self.n_iterations):
            indices = np.random.permutation(n_samples)
            X_shuffled = X[indices]
            y_shuffled = y[indices]

            for i in range(0, n_samples, self.batch_size):
                X_batch = X_shuffled[i:i + self.batch_size]
                y_batch = y_shuffled[i:i + self.batch_size]

                y_predicted = np.dot(X_batch, self.weights)
                gradients = (2 / self.batch_size) * np.dot(X_batch.T, (y_predicted - y_batch))
                self.weights -= self.learning_rate * gradients

    def predict(self, X):
        return np.dot(X, self.weights)

X_train = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y_train = np.array([1, 2, 2, 3])
model = MiniBatchGradientDescent(batch_size=2)
model.fit(X_train, y_train)
print(model.predict(np.array([[3, 5]])))

[4.99428493]


13. Problem: Implement k-means clustering from scratch. Given a dataset and the number of
clusters k , return the cluster assignments for each data point.

In [18]:
class KMeans:
    def __init__(self, k=3, max_iters=100):
        self.k = k
        self.max_iters = max_iters

    def fit(self, X):
        n_samples, n_features = X.shape
        random_indices = np.random.choice(n_samples, self.k, replace=False)
        self.centroids = X[random_indices]

        for _ in range(self.max_iters):
            labels = self._get_labels(X)
            self.centroids = self._get_centroids(X, labels)

    def _get_labels(self, X):
        distances = np.linalg.norm(X[:, np.newaxis] - self.centroids, axis=2)
        return np.argmin(distances, axis=1)

    def _get_centroids(self, X, labels):
        return np.array([X[labels == i].mean(axis=0) for i in range(self.k)])

    def predict(self, X):
        return self._get_labels(X)

X_train = np.array([[1, 2], [1, 4], [1, 0], [4, 2], [4, 4], [4, 0]])
kmeans = KMeans(k=2)
kmeans.fit(X_train)
print(kmeans.predict(X_train))

[1 1 1 0 0 0]


14. Problem: Implement a Python function to calculate the softmax of a list of numbers, which is used in multi-class classification problems.

In [20]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / exp_x.sum(axis=0)
scores = [1.0, 2.0, 3.0]
print(softmax(scores))

[0.09003057 0.24472847 0.66524096]


15. Problem: Write a Python function to compute the TF-IDF (Term Frequency-Inverse
Document Frequency) for a list of documents.

In [23]:
from collections import Counter
import math

def tf_idf(documents):
    tf = []
    idf = {}
    total_documents = len(documents)

    for doc in documents:
        counter = Counter(doc)
        tf.append({word: count / len(doc) for word, count in counter.items()})

    for doc in documents:
        for word in set(doc):
            idf[word] = idf.get(word, 0) + 1

    idf = {word: math.log(total_documents / count) for word, count in idf.items()}

    tf_idf_result = []
    for doc_tf in tf:
        doc_result = {word: doc_tf[word] * idf[word] for word in doc_tf}
        tf_idf_result.append(doc_result)

    return tf_idf_result

documents = [["Hi", "my", "name", "is", "Fayaz"], ["Hi", "my", "name", "is", "Abdul"]]
print(tf_idf(documents))

[{'Hi': 0.0, 'my': 0.0, 'name': 0.0, 'is': 0.0, 'Fayaz': 0.13862943611198905}, {'Hi': 0.0, 'my': 0.0, 'name': 0.0, 'is': 0.0, 'Abdul': 0.13862943611198905}]


16. Problem: Implement an algorithm to find the principal components of a dataset using
singular value decomposition (SVD), which is a core part of PCA (Principal Component
Analysis).

In [24]:
def pca(X, n_components):
    X_meaned = X - np.mean(X, axis=0)
    U, S, Vt = np.linalg.svd(X_meaned)
    W = Vt.T[:, :n_components]
    return X_meaned @ W

X = np.array([[2, 3], [3, 4], [4, 5]])
print(pca(X, n_components=1))

[[-1.41421356]
 [ 0.        ]
 [ 1.41421356]]


17. Problem: Write a Python function to calculate the AUC-ROC score for a binary
classification problem, given the true labels and predicted probabilities.

In [33]:
from sklearn.metrics import roc_auc_score
def calculate_auc_roc(y_true, y_scores):
    return roc_auc_score(y_true, y_scores)
y_true = [0, 0, 1, 1]
y_scores = [0.1, 0.4, 0.35, 0.8]
print(calculate_auc_roc(y_true, y_scores))

0.75


18. Problem: Implement a Python function to apply dropout regularization to the neurons of a given neural network during training.

In [34]:
import random

def dropout(layer, rate):
    return [neuron if random.random() > rate else 0 for neuron in layer]

layer = [0.5, 0.3, 0.9]
print(dropout(layer, rate=0.5))

[0, 0, 0.9]


19. Problem: Write a Python function to perform feature scaling using standardization (z-score normalization), which transforms features to have a mean of 0 and a standard deviation of 1.

In [4]:
def standardize(X):
    mean = np.mean(X, axis=0)
    std_dev = np.std(X, axis=0)
    return (X - mean) / std_dev

X = np.array([[1, 2], [3, 4], [5, 6]])
print(standardize(X))

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


20. Problem: Implement a Python function to compute the cross-entropy loss for a multi-class classification problem, given the true labels and predicted probabilities.

In [3]:
import numpy as np
def cross_entropy_loss(y_true, y_pred):
    epsilon = 1e-12  
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)  # Prevent NaNs
    return -np.mean(y_true * np.log(y_pred))

y_true = np.array([1, 0, 1])
y_pred = np.array([0.9, 0.1, 0.8])
print(cross_entropy_loss(y_true, y_pred))

0.10950135565734533
