In [11]:
#second largest element
l=[3,2,56,7,89,89,23]
l=list(set(l))
l.sort()
print(l[-2])

56


In [5]:
#prime number
num=15
l=[fa for fa in range(1,num+1) if num%fa==0]
print(len(l)==2)

False


In [6]:
#slicing reversing a string
s="vinod kumar neerugundla"
print(s[::-1])

aldnugureen ramuk doniv


In [7]:
#indexing reversing a string
s="vinod kumar neerugundla"
s1=""
for ind in range(-1,-len(s)-1,-1):
    s1+=s[ind]
print(s1)
    

aldnugureen ramuk doniv


In [14]:
L1=[1,2,3,2,8]
L2=[9,7,6,5,8]
L1.extend(L2)
L1.sort()
print(L1)

[1, 2, 2, 3, 5, 6, 7, 8, 8, 9]


In [16]:
#Factorial
def factorial(n):
    if n==0:
        return 1
    return n*factorial(n-1)
print(factorial(5))

120


In [17]:
#palindrome
S='MALAYALAM'
print(S==S[::-1])

True


In [23]:
#frequency of the elements
L=[1,2,3,4,5,6,1,2,3,2,3,4,5]
L2=list(set(L))

for el in L2:
    
    print(f"{el}:{str(L.count(el))}")

1:2
2:3
3:3
4:2
5:2
6:1


In [104]:
#fibinocci
def fibinocci(first,second):
    for _ in range(10):
        yield first
        first,second=second,first+second
Value=fibinocci(0,1)
try:
    while True:
        print(next(Value))
except:
    print("limit reached")

0
1
1
2
3
5
8
13
21
34
limit reached


In [28]:
#remove duplicates from a list
l=[11,2,3,4,3,5,6,4,6,4]
print(list(set(l)))

[2, 3, 4, 5, 6, 11]


In [40]:
#anagram
S1="A gentleman"
S2="elegant man"
print(str(sorted(S1)).lower()==str(sorted(S2)).lower())

True


In [55]:
#decimal to binary
num=15
bin=''

while num!=0:
    rem=num%2
    bin+=str(rem)
    num//=2
print(int(bin[::-1]))

1111


In [62]:
#find pairs in an array
l=[1,4,5,6,8,2,7]
Sum=9
for j in range(len(l)-1):
    for i in range(1,len(l)):
        if l[j]+l[i]==Sum:
            print([l[j],l[i]])

[1, 8]
[4, 5]
[5, 4]
[2, 7]


In [44]:
#vowels and consonants
s="they contain the same characters"
vowel_count=0
consonant_count=0
s=str(''.join(s.split()))
for ch in s:
    if ch in "aeiou":
        vowel_count+=1
    else:
        consonant_count+=1
print(f"vowel_count={vowel_count}")
print(f"consonant_count={consonant_count}")
        

vowel_count=10
consonant_count=18


In [50]:
#Binary Search
l=[1,2,4,5,6,7,8,9,23,24,45]
user=23
lowest=0
highest=len(l)-1
mid=highest+lowest//2
for ind in range(len(l)):
    if l[ind]<user:
        highest=mid-1
    elif l[ind]>user:
        lowest=mid+1
    elif l[ind]==user:
        print(ind)
        break
else:
    print(-1)


8


In [69]:
#Check if a list is sorted
l=[1,5,3,7,4,9,23]
for ind in range(len(l)-1):
    if l[ind]>l[ind+1]:
        l[ind],l[ind+1]=l[ind+1],l[ind]
print(l)

[1, 3, 5, 4, 7, 9, 23]


In [66]:
#Sum if digits in a number
def SumDigits(num):
    if num==0:
        return 0
    return num%10+SumDigits(num//10)
print(SumDigits(12345))

15


In [70]:
#Transpose of matrix
import numpy as np
l=[[1,2,3],
   [4,5,6],
  [7,8,9]]
print(np.transpose(l))


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [71]:
#intersection of two list
L1=[1,2,3,4,5]
L2=[1,4,5,6,2]
L3=[]
for el in L1:
    if el in L2:
        L3.append(el)
print(L3)


[1, 2, 4, 5]


In [72]:
#intersection of two list
L1=[1,2,3,4,5]
L2=[1,4,5,6,2]
intersection=list(set(L1)&set(L2))
print(intersection)

[1, 2, 4, 5]


In [76]:
#permutaions of String
from itertools import permutations
s='abc'
print(list(permutations(s)))


[('a', 'b', 'c'), ('a', 'c', 'b'), ('b', 'a', 'c'), ('b', 'c', 'a'), ('c', 'a', 'b'), ('c', 'b', 'a')]


In [103]:
#contiguous subarray
l=[-2, 1, -3, 4, -1, 2, 1, -5]
MaxSum=0
L1=[]
Sum=0
l2=[]
for ind in range(len(l)):
    Sum=0
    l2=[]
    for ind1 in range(ind,len(l)):
        l2.append(l[ind1])
        Sum+=l[ind1]
        if Sum>MaxSum:
            MaxSum=Sum
            L1=l2.copy()
print(MaxSum)
print(L1)

        
    

6
[4, -1, 2, 1]


In [ ]:
l=[[1,2,3],
   [4,5,6],
  [7,8,9]]
